[gin]
domain="*.localhost"
port="8080"
env="debug"
origins=["http://localhost", "http://localhost:3000"]

[auth]
access_token_pub="atp123"
access_token_ttl=10
refresh_token_pub="rtp123"
refresh_token_ttl=3600

[cache]
address="redis-cache:6379"
password="dev"
id=0

[mongo]
uri="mongodb://localhost"
database_name="dev"